name: Deploy KDS Service to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'kds-service/**'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: 'kdsandwaiter'
  CONTAINER_APP_NAME: 'kds-service'
  RESOURCE_GROUP: 'res_no_18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and Push Docker Image
        working-directory: ./kds-service
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

      - name: Deploy to Azure Container App
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
